# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Monime < Formula
  desc ""
  homepage "https://monime.io"
  version "1.0.3"
  license "Apache 2.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/monimesl/monime-cli/releases/download/v1.0.3/monime_1.0.3_mac-os_x86_64.tar.gz"
    sha256 "fc5e50aa24545ad9cf998c606ebc1927257e489ccd3b53e95323fb1de5fdec8f"

    def install
      bin.install "monime"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/monimesl/monime-cli/releases/download/v1.0.3/monime_1.0.3_mac-os_arm64.tar.gz"
    sha256 "c72ccffe5e9ddb39905cc6b17b30f57b978cc72df9cf63b5d42e7d6e462bd1e3"

    def install
      bin.install "monime"
    end
  end
end
