# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Monime < Formula
  desc ""
  homepage "https://monime.io"
  version "1.0.0"
  license "Apache 2.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/monimesl/monime-cli/releases/download/v1.0.0/monime_1.0.0_mac-os_x86_64.tar.gz"
    sha256 "a273c609c63bced03bd41ba4a7cab4c7950560ed098be2a4daadf40f86ec9b26"

    def install
      bin.install "monime"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/monimesl/monime-cli/releases/download/v1.0.0/monime_1.0.0_mac-os_arm64.tar.gz"
    sha256 "0cdf62fe396c3a2084fbea8cccbd119aa338b1fd1f794396fd466f2ee8d86cdb"

    def install
      bin.install "monime"
    end
  end
end
