# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Monime < Formula
  desc ""
  homepage "https://monime.io"
  version "0.0.2"
  license "Apache 2.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/monimesl/monime-cli/releases/download/v0.0.2/monime_cli_0.0.2_macOS_amd64.tar.gz"
    sha256 "94f4e2c8685ec2040818eb8b4fe90ac31cda26aba1550f9ecabb65ad73880130"

    def install
      bin.install "monime"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/monimesl/monime-cli/releases/download/v0.0.2/monime_cli_0.0.2_macOS_arm64.tar.gz"
    sha256 "fd51098e972d3fa415c66f11ef2d7868780bdf439787bf971e71e7748bb85e82"

    def install
      bin.install "monime"
    end
  end
end
