# This file was generated by GoReleaser. DO NOT EDIT.
cask "monime" do
  desc ""
  homepage "https://monime.io"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "monime"

  on_macos do
    on_intel do
      url "https://github.com/monimesl/monime-cli/releases/download/v1.0.0/monime_1.0.0_mac-os_x86_64.tar.gz"
      sha256 "5f7fa1ef6c3fc8849f430e1efc8bab7546bfa104975e12252e7caf79ec70d06e"
    end
    on_arm do
      url "https://github.com/monimesl/monime-cli/releases/download/v1.0.0/monime_1.0.0_mac-os_arm64.tar.gz"
      sha256 "0d92c1059728dcbba5a66ab7b40f5ea2e247b7d55e916660d58f3c351a5ebe17"
    end
  end

  # No zap stanza required
end
