# This file was generated by GoReleaser. DO NOT EDIT.
cask "monime" do
  desc ""
  homepage "https://monime.io"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "monime"

  on_macos do
    on_intel do
      url "https://github.com/monimesl/monime-cli/releases/download/v1.0.0/monime_1.0.0_mac-os_x86_64.tar.gz"
      sha256 "d99f6a206fb36775d4e180978a703eec9abbbf4616cd5f745c8e9cbd575e0637"
    end
    on_arm do
      url "https://github.com/monimesl/monime-cli/releases/download/v1.0.0/monime_1.0.0_mac-os_arm64.tar.gz"
      sha256 "6317340e90faab40521273a2caae2326334766a447c4423fcfe168bdb7bb1320"
    end
  end

  # No zap stanza required
end
