# This file was generated by GoReleaser. DO NOT EDIT.
cask "monime" do
  desc ""
  homepage "https://monime.io"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "monime"

  on_macos do
    on_intel do
      url "https://github.com/monimesl/monime-cli/releases/download/v1.0.0/monime_1.0.0_mac-os_x86_64.tar.gz"
      sha256 "6a5e76de92e5617183ab764fd61f61122112abdbf10b5845556cc650a0144aae"
    end
    on_arm do
      url "https://github.com/monimesl/monime-cli/releases/download/v1.0.0/monime_1.0.0_mac-os_arm64.tar.gz"
      sha256 "c7f15201302aef08fcc3a91efc2ca1388b5b914376aeff25f0c3104ba74d1ccf"
    end
  end

  # No zap stanza required
end
