# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Monime < Formula
  desc ""
  homepage "https://monime.io"
  version "1.0.0"
  license "Apache 2.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/monimesl/monime-cli/releases/download/v1.0.0/monime_1.0.0_mac-os_x86_64.tar.gz"
    sha256 "9c3f103381a088d863d69b4f994c332ba654e7a50b5db188481befdf4e128221"

    def install
      bin.install "monime"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/monimesl/monime-cli/releases/download/v1.0.0/monime_1.0.0_mac-os_arm64.tar.gz"
    sha256 "475b1b4184c76d56728abc20d4c277650a00cee09fd21d573755e61b8c2500cc"

    def install
      bin.install "monime"
    end
  end
end
